### ISSUE TITLE
Encountered Docker Error: "When using COPY with more than one source file, the destination must be a directory and end with a /""

### ISSUE THREAD

**Issue by PabloTheDeveloper** [olliefr/docker-gs-ping#1]
**OS & Docker version**
My docker version: 20.10.7, build f0df35096d
OS: arch-linux

**Reproducing the Error:**
Good day olliefr, I encountered an error when going through the golang docker [tutorial.](https://docs.docker.com/language/golang/build-images/)

The following commands were run:
`git clone https://github.com/olliefr/docker-gs-ping`
`cd docker-gs-ping`
`docker build --tag docker-gs-ping .`

**The Error** 
`
When using COPY with more than one source file, the destination must be a directory and end with a /
`

**The Solution**
By changing line 12 in the Dockerfile from:
`COPY *.go .`
to
`COPY *.go ./`

I am not sure if this solution will cause other issues. I doubt it but I can investigate and make a pull request if this error is significant enough.

I am also curious if other people encountered this error or if it is only on my machine.

**Comment by olliefr** [comment]
Hello, @PabloTheDeveloper and thank you for taking your time to submit a bug report!

I think you are right! After careful reading of the [Dockerfile reference](https://docs.docker.com/engine/reference/builder/#copy), I think that the syntax you suggested is the correct one.

Having said that, I've just tested the `Dockerfile` as it is on my instance of Docker and it works:

![image](https://user-images.githubusercontent.com/967105/126846517-3a03dfe4-83c0-4561-b4b7-70d2d3886ac6.png)

I still believe that your suggested solution is the right one, please bear with me while I investigate further and update the code and the docs.

In answer to your other question, you are the first one to report this to me 😄

**Comment by thiberaw** [comment]
Hello both of you,

I did encounter the same issue and was about to open a pull request.

Here a few more information
`➜  docker-gs-ping git:(missing-slash-character) ✗ docker version
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`
Running on `Ubuntu 20.04.2 LTS`
