### ISSUE TITLE
Go version no longer officially supported

### ISSUE THREAD

**Issue by craig-osterhout** [olliefr/docker-gs-ping#8]
Hi @olliefr,

Since Go 1.16 is no longer officially supported, can this sample be updated to a newer version?
If necessary, I can help create a PR here and in the Docker Docs if no concerns.

**Comment by olliefr** [comment]
Hi @craig-osterhout!

Thank you for noticing this. It's been a while since I worked on this application. Please feel free to submit a PR and I will approve as a matter of priority :shipit:

**Comment by olliefr** [comment]
Hey, @craig-osterhout, just wanted to let you know that I've begun work on updating the Golang guide to v1.19. I also have plans to simplify some Golang sections a bit and to add some new info on deploying to Cloud Run.

The update to docs is tracked in the following branch:
https://github.com/olliefr/docker.github.io/tree/olliefr-update-golang

The update to the source code for the example application is coming as a feature branch to this repo...

**Comment by olliefr** [comment]
[v0.0.4](https://github.com/olliefr/docker-gs-ping/releases/tag/v0.0.4) was just released, based on Go 1.19 and the latest version of the dependencies. I will close this issue once I submit a PR for updating the docs...

**Comment by olliefr** [comment]
Now that the PR to update the docs has been submitted, I can close this 🙃
